### PR TITLE
Porcinus Configuration Tool, EvTestValues Script, Install Script Update

### PR DESCRIPTION
**Pull request by Mootikins**

### CODE REVIEW

**Comment by porcinus** [comment]
[Do not merge, tested only with ADS1015 for now]
Are you interested to add the updated version of the driver?
- It use the ADC_OffsetCenter() function whatever Auto Center is enable or not. When Auto Center not enable,  the offset value is set at midpoint between min and max.
- Possible offset overflow fixed.
- Additional debug output.

**Comment by TheFlav** [comment]
> [Do not merge]
> Are you interested to add the updated version of the driver?
> It use the ADC_OffsetCenter() function whatever Auto Center is enable.
> When Auto Center not enable, the offset value is set at midpoint between min and max.

I'm sorry.  I have had so many little/new things grab my attention lately, it's hard to keep up.  I will leave this to @Mootikins to test and recommend to me when it's ready to merge.  He is usually able to talk to me directly, but he has family coming to town today.  I think he will not be able to work on it much until tomorrow.

**Comment by porcinus** [comment]
> 
> 
> > [Do not merge]
> > Are you interested to add the updated version of the driver?
> > It use the ADC_OffsetCenter() function whatever Auto Center is enable.
> > When Auto Center not enable, the offset value is set at midpoint between min and max.
> 
> I'm sorry. I have had so many little/new things grab my attention lately, it's hard to keep up. I will leave this to @Mootikins to test and recommend to me when it's ready to merge. He is usually able to talk to me directly, but he has family coming to town today. I think he will not be able to work on it much until tomorrow.

No problem ;)

**Comment by porcinus** [comment]
For whatever reason, I didn't thinked about this before, the driver I use for my WiFi module run via DKMS and is able to keep up after kernel update since last kernel headers are backup.

But it require a little tweak when I want to recompile it by hand with the new kernel, I need to create a symlink into the kernel headers 'arch' folder between 'arm' and 'armv7'.

Don't know if it can help :s

https://github.com/porcinus/rtl8188fu

**Comment by Mootikins** [comment]
Porcinus, I have made some changes to master based on your changes thus far. Have not made menu script and may just remove altogether, opting instead to have them run a `make config` command to build and run the binary. This way, they do everything in one go since they more than likely won't be changing the binding more than once or twice. Take a look at the changes and see if there is anything you would like me to add.

EDIT: I have not yet looked into the symlink between `arm` and `armv7` directories, where are they so that I can give it a try?

**Comment by porcinus** [comment]
For the kernel, it is in '/usr/src/linux-headers-4.14.98-v7+/arch', you need to make a symlink from 'armv7l' to 'arm'.

**Comment by porcinus** [comment]
For the config stuff, I think this should be good to keep both, as you said, most users don't change there config so often, in fact they don't even go into Retropie menu after setup done but it is (for me) a good idea to keep, just in case.

Take the problem in the other way, most users never update there driver, if a user add analog stick but doesn't have any SSH knowledge but want to edit the joystick config, there is a possible that this will end up with a mess.

In readme, 'backs up your old emulationstation bindings', where do you make this backup? the program only backup driver config.

You should check the pull request I made on your Git, mk_joystick_config.cpp and mk_arcade_joystick_rpi.c are outdated :S

**Comment by Mootikins** [comment]
Thank you for reminder, will also make the script add a menu option. Will also talk with Flav when he gets back from vacation about possibly making a new system menu similar to RetroPie's now that I know how to do so.

**Comment by porcinus** [comment]
> 
> 
> Thank you for reminder, will also make the script add a menu option. Will also talk with Flav when he gets back from vacation about possibly making a new system menu similar to RetroPie's now that I know how to do so.

Misunderstood about the config file, I was thinking about '/opt/retropie/configs/all/emulationstation/es_input.cfg'.
'/etc/modprobe.d/mk_arcade_joystick.conf' backup is done by the software with a timestamp.

Making a specific system menu can be a good idea ;)

For the menu item : https://github.com/porcinus/mk_arcade_joystick_rpi/blob/69431dd18c79f033fd225908598df3ccd1339148/install.sh#L63

**Comment by porcinus** [comment]
whatsapp or anything text messenger?

**Comment by Mootikins** [comment]
I could but I don't want to bother him on his week off with kids (anymore than he already has been by github emails). I think this is at a mostly mergeable state so I will leave it until he returns next week.

**Comment by porcinus** [comment]
I didn't even think about this :/
You are totally right :)
It is a little late now in France, I will start a long weekend tomorrow, if it's ok for you, i will send you all additional modifications I found on the mail used in your page.

**Pull request merged**
